### ISSUE TITLE
M_PI is not supposed to be defined in C99

### ISSUE THREAD

**Issue by Xfennec** [coreh/gl-matrix.c#1]
The code is compiled with `-std=c99` flag, but the C99 standard dropped M_PI and all other mathc defines of the same type. When compiling a compiler that strictly respects ISO like `gcc`, it generates a M_PI undefined error.

You should probably define your own PI, or compile with `-std=gnu99` flag, for instance.

**Comment by coreh** [comment]
Thanks for pointing it out! Added my own.
